import type { Creature } from '../types/world';
export const CREATURES: Record<string, Creature> = {
  sylve: {
    id: 'sylve',
    name: 'Barbemousse',
    family: 'sylve',
    tier: 1,
    color: '#8056c7',
    accent: '#57c598',
    hp: 24,
    attack: 8,
    defense: 3,
    speed: 3,
    range: 1,
    ability: 'root',
    description:
      'Un petit gardien à la barbe verte. ' +
      'Ses racines ralentissent la cible après une attaque.',
    evolves: ['sylve-guard', 'sylve-druid'],
    gold: 70,
    crystals: 0,
    xp: 0,
  },
  'sylve-guard': {
    id: 'sylve-guard',
    name: 'Gardien des bois',
    family: 'sylve',
    tier: 2,
    color: '#5e4da1',
    accent: '#57e2be',
    hp: 38,
    attack: 11,
    defense: 8,
    speed: 3,
    range: 1,
    ability: 'guard',
    description:
      'Une armure de feuilles et un cœur de chêne. Réduit les dégâts de 25 %.',
    evolves: ['sylve-ancient'],
    gold: 240,
    crystals: 4,
    xp: 45,
  },
  'sylve-druid': {
    id: 'sylve-druid',
    name: 'Druide émeraude',
    family: 'sylve',
    tier: 2,
    color: '#6a53ba',
    accent: '#72ead0',
    hp: 29,
    attack: 13,
    defense: 4,
    speed: 4,
    range: 3,
    ability: 'heal',
    description:
      'Sa barbe lumineuse canalise la forêt. ' +
      'Récupère des points de vie après chaque attaque.',
    evolves: ['sylve-ancient'],
    gold: 240,
    crystals: 4,
    xp: 45,
  },
  'sylve-ancient': {
    id: 'sylve-ancient',
    name: 'Ancêtre de Sylve',
    family: 'sylve',
    tier: 3,
    color: '#574386',
    accent: '#92ffcf',
    hp: 52,
    attack: 19,
    defense: 9,
    speed: 4,
    range: 3,
    ability: 'heal',
    description:
      'Des bois majestueux, une magie ancienne. ' +
      'Puissant gardien capable de se régénérer.',
    evolves: [],
    gold: 480,
    crystals: 9,
    xp: 120,
  },
  sol: {
    id: 'sol',
    name: 'Pompon solaire',
    family: 'sol',
    tier: 1,
    color: '#cb66c3',
    accent: '#ffd657',
    hp: 18,
    attack: 9,
    defense: 2,
    speed: 4,
    range: 3,
    ability: 'spark',
    description:
      'Sa houppe jaune crépite de magie. ' +
      'Tire des étincelles sur le champ de bataille, ' +
      'avec une pénalité à longue distance.',
    evolves: ['sol-flame', 'sol-star'],
    gold: 85,
    crystals: 0,
    xp: 0,
  },
  'sol-flame': {
    id: 'sol-flame',
    name: 'Crête de braise',
    family: 'sol',
    tier: 2,
    color: '#dd78a4',
    accent: '#ff9b49',
    hp: 27,
    attack: 16,
    defense: 3,
    speed: 5,
    range: 3,
    ability: 'spark',
    description:
      'Une crête ardente et des étincelles plus fortes. ' +
      'Ses attaques infligent 20 % de dégâts supplémentaires.',
    evolves: ['sol-phoenix'],
    gold: 260,
    crystals: 4,
    xp: 45,
  },
  'sol-star': {
    id: 'sol-star',
    name: 'Oracle étoilé',
    family: 'sol',
    tier: 2,
    color: '#9e72dc',
    accent: '#fff0a0',
    hp: 26,
    attack: 13,
    defense: 5,
    speed: 5,
    range: 4,
    ability: 'drain',
    description:
      'Lit les constellations et absorbe la lumière. ' +
      'Ses attaques restaurent une partie de ses points de vie.',
    evolves: ['sol-phoenix'],
    gold: 260,
    crystals: 4,
    xp: 45,
  },
  'sol-phoenix': {
    id: 'sol-phoenix',
    name: 'Phénix d’aurore',
    family: 'sol',
    tier: 3,
    color: '#d086d9',
    accent: '#ffdd88',
    hp: 40,
    attack: 23,
    defense: 6,
    speed: 6,
    range: 4,
    ability: 'drain',
    description:
      'Couronné de plumes et d’ailes dorées. ' +
      'La forme ultime des Pompons solaires.',
    evolves: [],
    gold: 500,
    crystals: 9,
    xp: 120,
  },
};
